apiVersion: "config.istio.io/v1alpha2"
kind: helloquota
metadata:
  name: handler
  namespace: istio-system
spec:
  quotas:
    - name: requestcount.quota.istio-system
      maxAmount: 500
      validDuration: 1s
      bucketDuration: 500ms
      rateLimitAlgorithm: <rate_limit_algorithm>
      # The first matching override is applied.
      # A requestcount instance is checked against override dimensions.
      overrides:
        # The following override applies to 'reviews' regardless
        # of the source.
        - dimensions:
            destination: reviews
          maxAmount: 1
          validDuration: 5s
        # The following override applies to 'productpage' when
        # the source is a specific ip address.
        - dimensions:
            destination: productpage
            source: "10.28.11.20"
          maxAmount: 500
          validDuration: 1s
        # The following override applies to 'productpage' regardless
        # of the source.
        - dimensions:
            destination: productpage
          maxAmount: 2
          validDuration: 5s
      helloServerUrl: <hello_server_url>
      connectionPoolSize: 10
---
apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: requestcount
  namespace: istio-system
spec:
  dimensions:
    source: request.headers["x-forwarded-for"] | "unknown"
    destination: destination.labels["app"] | destination.workload.name | "unknown"
    destinationVersion: destination.labels["version"] | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  # quota only applies if you are not logged in.
  # match: match(request.headers["cookie"], "user=*") == false
  actions:
    - handler: handler.helloquota
      instances:
        - requestcount.quota
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
    - quotas:
        - charge: 1
          quota: requestcount
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
    - name: request-count
      namespace: istio-system
  services:
    - name: productpage
      namespace: default
      #  - service: '*'  # Uncomment this to bind *all* services to request-count
---