apiVersion: v1
kind: Service
metadata:
  name: bash-service
  labels:
    app: bash-service
  namespace: hs
spec:
  ports:
    - port: 3000
      name: http
#       nodePort: 31313
  clusterIP: None
#  type: NodePort
  selector:
    app: bash-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bash-service
#  labels:
#    app: bash-service
  namespace: hs
spec:
  serviceName: bash-service
  replicas: 2
  selector:
    matchLabels:
      app: bash-service
  template:
    metadata:
      labels:
        app: bash-service
    spec:
      containers:
      - name: hsnode-container
        image: jonas27/hello:v5
        imagePullPolicy: Always
#        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: testport
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
#      nodeSelector:
#        beta.kubernetes.io/os: linux
#        accelerator: nvidia
