apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.nodeServiceName . }}
  labels:
    app: vpsnode
  namespace: {{ .Release.Namespace }}
spec:
   type: NodePort
   ports:
     - port: {{ .Values.nodeServicePortTK }}
       name: toolkit
     - port: 3000
       nodePort: 31314
       name: http
   selector:
     app: vpsnode
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-node-daemonset
  labels:
    app: vpsnode
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: vpsnode
  template:
    metadata:
      labels:
        app: vpsnode
        provider: ms-ct
    spec:
      containers:
      - name: {{ .Release.Name }}-node-container
        image: {{ .Values.platform }}{{ .Values.projectID }}/vpsnode_ctrt{{ .Values.imageSuffix }}:ubuntu_18.04
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.nodeContainerPortGRPC }}
          name: grpc
        - containerPort: {{ .Values.nodeServicePortTK }}
          name: toolkit
      - name: hello
        image: jonas27/hello:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
      nodeSelector:
        beta.kubernetes.io/os: linux
        accelerator: nvidia
