apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-route
  namespace: default
spec:
  hosts:
    - hello # interpreted as reviews.foo.svc.cluster.local
  http:
    - match: # only allow traffic matching these constraints
        - uri:
            prefix: "/hello"
      rewrite:
        uri: "/hello"
      route:
        - destination:
            host: hello # interpreted as hello.default.svc.cluster.local
            subset: v3
          weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello-destination
  namespace: default
spec:
  host: hello # interpreted as reviews.foo.svc.cluster.local
  subsets:
    - name: v3
      labels:
        version: v3
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30ms
