#!/bin/bash

# Important

Helm template creates NodePort use this command <br />
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
--set gateways.istio-ingressgateway.type=NodePort \
--set gateways.istio-egressgateway.type=NodePort > installIstio 

--set sidecarInjectorWebhook.enabled=fals2 \     --> supposed to help for sidecar injection but no
```


Foward <br /> 
Prom 
```
kubectl -n istio-system port-forward --address 0.0.0.0 \
$(kubectl -n istio-system get pod -l app=prometheus -o jsonpath='{.items[0].metadata.name}') \
9090:9090 & > promForward
```
Graf 
```
kubectl -n istio-system port-forward --address 0.0.0.0 \
$(kubectl -n istio-system get pod -l app=grafana -o jsonpath='{.items[0].metadata.name}') \
5000:3000 & > grafForward
```
Jaeger 
```
kubectl -n istio-system port-forward --address 0.0.0.0 \
$(kubectl -n istio-system get pod -l app=jaeger -o jsonpath='{.items[0].metadata.name}') \
16686:16686 & > jaegerForward
```
Service Graph
```
kubectl -n istio-system port-forward --address 0.0.0.0 \
$(kubectl -n istio-system get pod -l app=servicegraph -o jsonpath='{.items[0].metadata.name}') \
8088:8088 & > serviceGraphForward
```



look for istio proxy and pod stuff
```
kubectl describe pods hello 
```

normal bookinfo install does not install promotheus dependencies. no its running

systest
test.


Commands for port forwarding local to VB:
VBoxManage modifyvm ubuntu-fresh --natpf1 "ssh,tcp,,3022,,22" && \
VBoxManage modifyvm ubuntu-fresh --natpf1 "ingress,tcp,,31380,,31380" && \
VBoxManage modifyvm ubuntu-fresh --natpf1 "ingressTLS,tcp,,31390,,31390" && \
VBoxManage modifyvm ubuntu-fresh --natpf1 "prom,tcp,,9090,,9090" && \
VBoxManage modifyvm ubuntu-fresh --natpf1 "graf,tcp,,5000,,5000" && \
VBoxManage modifyvm ubuntu-fresh --natpf1 "jaeger,tcp,,16686,,16686" && \
VBoxManage modifyvm ubuntu-fresh --natpf1 "servGraph,tcp,,8088,,8088"

kubectl -n istio-system port-forward --address 0.0.0.0 \
$(kubectl -n istio-system get pod -l app=prometheus -o jsonpath='{.items[0].metadata.name}') \
9090:9090 & \
kubectl -n istio-system port-forward --address 0.0.0.0 \
$(kubectl -n istio-system get pod -l app=grafana -o jsonpath='{.items[0].metadata.name}') \
5000:3000 & \
kubectl -n istio-system port-forward --address 0.0.0.0 \
$(kubectl -n istio-system get pod -l app=jaeger -o jsonpath='{.items[0].metadata.name}') \
16686:16686 & \
kubectl -n istio-system port-forward --address 0.0.0.0 \
$(kubectl -n istio-system get pod -l app=servicegraph -o jsonpath='{.items[0].metadata.name}') \
8088:8088 &
