#!/bin/bash

# prepare system
export USERNAME=$(read -p 'Username: ' uval && echo -n $uval) && \
sudo apt update && \
sudo apt install -y snapd curl docker.io && \
sudo systemctl enable docker && \
sudo apt-get install -y openssh-server && \
sudo apt update && \
sudo snap install helm --classic

printf "***Install kubeadm and swapoff***" && \
printf "*** Install kubeadm and swapoff ***" && \
sudo apt-get update && \
sudo apt-get install -y apt-transport-https && \
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && \
echo deb https://apt.kubernetes.io/ kubernetes-xenial main | sudo tee -a /etc/apt/sources.list.d/kubernetes.list && \
printf " download deb https://apt.kubernetes.io/ kubernetes-xenial main" && \
sudo apt-get update && \
sudo apt-get install -y kubelet kubeadm kubectl && \
sudo apt-mark hold kubelet kubeadm kubectl && \
sudo swapoff -a && \
printf "*** Swap is off! ***"

printf "***Configure kubernetes***" && \
# sudo hostnamectl set-hostname ubuntu-kubernetes-master && \
sudo kubeadm init --pod-network-cidr=10.244.0.0/16 >> joinConfigs && \
printf "*** Outputs kube join url with token and next run with run on single node ***" && \
sudo kubectl taint nodes --all node-role.kubernetes.io/master-

printf "*** Use kubectl without sudo (user here is joe ***" && \
mkdir -p $HOME/.kube && \
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && \
sudo chown $USER $HOME/.kube/config

printf "*** nstall components (if pods pending there is probably routing problem --> install flannel ***"
printf "*** install Flannel for networking***"
sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
printf "*** install k8s dashboard***"
sudo kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml

printf "*** Outputs kube join url with token and next run with run on single node ***" && \
sudo kubectl taint nodes --all node-role.kubernetes.io/master-

# Create sample user
#kubectl create -f https://raw.githubusercontent.com/jonas27/istioKubTesting/master/helloService/sampleUser
sed -i -e '$a\export ALL="kubectl get all --all-namespaces"' $HOME/.profile

